# Application Configuration
cloud.microservice.namespace=${NAMESPACE:local}
cloud.microservice.name=${MICROSERVICE_NAME:qubership-nifi}
quarkus.application.name=${MICROSERVICE_NAME:qubership-nifi}

# Consul Configuration
quarkus.consul-source-config.enabled=${CONSUL_ENABLED:true}
quarkus.consul-source-config.agent.url=${CONSUL_URL:http://localhost:8500}
quarkus.consul-source-config.properties-root=config/${cloud.microservice.namespace}/application,config/${cloud.microservice.namespace}/${cloud.microservice.name}
#Maximum wait time for Consul blocking queries (in seconds)
quarkus.consul-source-config.wait-time=20
quarkus.consul-source-config.m2m.enabled=false
# Property-based token storage:
quarkus.consul.acl-token.enabled=true
quarkus.consul.acl-token.token=${CONSUL_ACL_TOKEN:}

# NiFi Configuration Paths
nifi.config.path=${NIFI_HOME:/opt/nifi}/conf/
nifi.notification.path=/tmp/
nifi.config.main.path=${NIFI_HOME:/opt/nifi}/persistent_conf/conf/
nifi.config.restore.path=${NIFI_HOME:/opt/nifi}/persistent_conf/conf-restore/

# Application Settings
quarkus.banner.enabled=false

# Logging Configuration
quarkus.log.level=${ROOT_LOG_LEVEL:INFO}
quarkus.log.console.enabled=true
quarkus.log.console.format=[%d{yyyy-MM-dd'T'HH:mm:ss.SSS}][%-5p] [thread=%-30.30t] [class=%-60.60c{59}] [method=%-30.30M] [traceId=%-16X{traceId:--}] [spanId=%-16X{spanId:--}] %m%n

# Disable live reload and dev mode features for production
quarkus.live-reload.instrumentation=false
